#!/usr/bin/env python3
"""Run a non-AlphaFold MSA-free single-sequence structure-source probe.

This script is intentionally an adapter, not a bundled neural predictor.  It can
consume a PDB generated by an MSA-free predictor such as ESMFold/OmegaFold, or it
can execute an opt-in local prediction command with a hard timeout.
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Mapping, Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from pharmacotopology.folding_coupling_nucleus_selector import (  # noqa: E402
    build_coupling_nucleus_context,
    select_coupling_trace_loop_aggressive_relative_frontier_events,
    select_coupling_trace_loop_self_deciding_frontier_generated_events,
)
from pharmacotopology.folding_evolutionary_constraints import load_coupling_dataset  # noqa: E402
from pharmacotopology.folding_independent_contact_evidence import (  # noqa: E402
    INDEPENDENT_CONTACT_ENSEMBLE_KIND,
    candidate_region_evidence_from_events,
    contact_evidence_from_predicted_pdb,
    coupling_contact_evidence,
    evaluate_ensemble_contacts,
    sequence_physical_prior_contact_evidence,
    write_contact_evidence_json,
)
from pharmacotopology.folding_native_contact_eval import (  # noqa: E402
    contact_map_hash,
    evaluate_contact_prediction,
)
from pharmacotopology.folding_nucleus_closure_search import NucleusClosureEvent  # noqa: E402
from pharmacotopology.folding_real_coordinate_visual_benchmark import (  # noqa: E402
    RealCoordinateVisualRow,
    load_real_coordinate_visual_rows,
)
from pharmacotopology.folding_single_sequence_structure_source import (  # noqa: E402
    SINGLE_SEQUENCE_STRUCTURE_CONTACT_SOURCE_KIND,
    SINGLE_SEQUENCE_STRUCTURE_REPORT_KIND,
    run_single_sequence_prediction_source,
)


DEFAULT_BENCHMARK_FILE = REPO_ROOT / "data" / "folding_real_coordinate_visual_8.locked.json"
DEFAULT_COUPLING_FILE = REPO_ROOT / "data" / "folding_real_coordinate_visual_8_external_couplings.v0.locked.json"
DEFAULT_OUT_DIR = REPO_ROOT / "first_contact_clean_pharmacotopology_layer_run" / "msa_free_single_sequence_structure_v0"


def _csv_write(path: Path, rows: Sequence[Mapping[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def _row_by_accession(rows: Sequence[RealCoordinateVisualRow], accession: str) -> RealCoordinateVisualRow:
    matches = [row for row in rows if row.source_accession == accession]
    if len(matches) != 1:
        raise SystemExit(f"expected exactly one row for {accession}, found {len(matches)}")
    return matches[0]


def _events_for_source(*, row: RealCoordinateVisualRow, context, event_source: str) -> tuple[NucleusClosureEvent, ...]:
    if event_source == "aggressive_relative_frontier":
        events = select_coupling_trace_loop_aggressive_relative_frontier_events(context)
    elif event_source == "self_deciding_generated_frontier":
        events = select_coupling_trace_loop_self_deciding_frontier_generated_events(context)
    else:
        raise ValueError(f"unknown event source: {event_source}")
    return tuple(event for event in events if event.row_id == row.row_id)


def _family_counts(evidence) -> dict[str, int]:
    grouped: dict[str, set[tuple[int, int]]] = {}
    for item in evidence:
        grouped.setdefault(item.source_family, set()).add(item.pair())
    return {family: len(pairs) for family, pairs in sorted(grouped.items())}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run a bounded MSA-free single-sequence structure-source contact ensemble probe."
    )
    parser.add_argument("--benchmark-file", default=str(DEFAULT_BENCHMARK_FILE))
    parser.add_argument("--external-coupling-file", default=str(DEFAULT_COUPLING_FILE))
    parser.add_argument("--source-accession", default="4AKE:A")
    parser.add_argument(
        "--event-source",
        default="aggressive_relative_frontier",
        choices=("aggressive_relative_frontier", "self_deciding_generated_frontier"),
    )
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    parser.add_argument(
        "--predicted-pdb",
        default=None,
        help="PDB already generated by an MSA-free predictor such as ESMFold/OmegaFold.",
    )
    parser.add_argument(
        "--prediction-command",
        default=None,
        help=(
            "Optional local command to generate a PDB. Placeholders: {fasta}, "
            "{output_pdb}, {source_accession}, {row_id}, {sequence_length}."
        ),
    )
    parser.add_argument("--predicted-pdb-chain", default=None)
    parser.add_argument("--predicted-source-id", default="custom_single_sequence_structure_model")
    parser.add_argument("--timeout-seconds", type=float, default=120.0)
    parser.add_argument("--keep-query-fasta", action="store_true")
    parser.add_argument("--allow-alphafold-source", action="store_true")
    parser.add_argument("--include-sequence-physical-priors", action="store_true")
    parser.add_argument("--physical-prior-min-confidence", type=float, default=0.55)
    parser.add_argument("--min-votes", type=int, default=2)
    parser.add_argument("--solved-precision-threshold", type=float, default=0.70)
    parser.add_argument("--solved-recall-threshold", type=float, default=0.70)
    parser.add_argument("--fail-without-prediction", action="store_true")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    report_path = out_dir / "msa_free_single_sequence_structure_probe_report.json"
    decisions_path = out_dir / "msa_free_single_sequence_structure_probe_decisions.csv"
    selected_path = out_dir / "msa_free_single_sequence_structure_probe_selected_contacts.csv"
    evidence_path = out_dir / "msa_free_single_sequence_structure_probe_evidence.json"

    rows = tuple(load_real_coordinate_visual_rows(Path(args.benchmark_file)))
    row = _row_by_accession(rows, args.source_accession)
    coupling_dataset = load_coupling_dataset(Path(args.external_coupling_file))
    context = build_coupling_nucleus_context(rows=rows, coupling_dataset=coupling_dataset)
    events = _events_for_source(row=row, context=context, event_source=args.event_source)
    constraints = tuple(coupling_dataset.constraints_by_row_id().get(row.row_id, ()))

    candidate_region_evidence = candidate_region_evidence_from_events(row=row, events=events)
    evidence = []
    evidence.extend(candidate_region_evidence)
    evidence.extend(coupling_contact_evidence(row=row, constraints=constraints))
    if args.include_sequence_physical_priors:
        evidence.extend(
            sequence_physical_prior_contact_evidence(
                row=row,
                candidate_pairs=[item.pair() for item in candidate_region_evidence],
                min_confidence=args.physical_prior_min_confidence,
            )
        )

    predicted_pdb = Path(args.predicted_pdb) if args.predicted_pdb else out_dir / "single_sequence_prediction.pdb"
    source_run = run_single_sequence_prediction_source(
        row=row,
        predicted_pdb_path=predicted_pdb,
        predictor_source_id=args.predicted_source_id,
        prediction_command=args.prediction_command,
        timeout_seconds=args.timeout_seconds,
        keep_query_fasta=args.keep_query_fasta,
        allow_alphafold_source=args.allow_alphafold_source,
        working_directory=out_dir,
    )

    predictor_parse_error = ""
    direct_structure_pairs: tuple[tuple[int, int], ...] = ()
    if source_run.status == "prediction_available":
        try:
            structure_evidence = contact_evidence_from_predicted_pdb(
                row=row,
                pdb_path=Path(source_run.predicted_pdb_path),
                chain_id=args.predicted_pdb_chain,
                source_id=args.predicted_source_id,
                source_kind=SINGLE_SEQUENCE_STRUCTURE_CONTACT_SOURCE_KIND,
                source_family="independent_structure",
            )
            direct_structure_pairs = tuple(item.pair() for item in structure_evidence)
            evidence.extend(structure_evidence)
        except Exception as exc:  # noqa: BLE001 - report parse failure rather than hang/crash by default
            predictor_parse_error = f"{type(exc).__name__}: {exc}"

    report, decisions, _metric = evaluate_ensemble_contacts(
        row=row,
        evidence_sources=tuple(evidence),
        min_votes_required=args.min_votes,
        require_candidate_region_support=True,
        require_independent_structure_support=True,
    )
    selected_decisions = tuple(decision for decision in decisions if decision.selected)
    selected_pairs = tuple(decision.pair() for decision in selected_decisions)

    direct_structure_metric = evaluate_contact_prediction(
        native_pairs=row.native_contact_pairs(),
        predicted_pairs=direct_structure_pairs,
    )
    native_long_pairs = {pair for pair in row.native_contact_pairs() if pair[1] - pair[0] >= 24}
    direct_long_pairs = {pair for pair in direct_structure_pairs if pair[1] - pair[0] >= 24}
    direct_long_tp = native_long_pairs & direct_long_pairs
    direct_long_precision = (
        round(len(direct_long_tp) / len(direct_long_pairs), 6) if direct_long_pairs else 0.0
    )

    direct_structure_solved = (
        source_run.status == "prediction_available"
        and not source_run.source_rejected
        and not source_run.alphafold_like_source_id
        and not source_run.raw_sequence_exposed_in_persisted_artifacts
        and not predictor_parse_error
        and direct_structure_metric.native_contact_precision >= args.solved_precision_threshold
        and direct_structure_metric.native_contact_recall >= args.solved_recall_threshold
    )
    ensemble_contact_collapse_solved = (
        report.benchmark_claim_allowed
        and report.contact_precision >= args.solved_precision_threshold
        and report.contact_recall >= args.solved_recall_threshold
        and not source_run.alphafold_like_source_id
        and not predictor_parse_error
    )
    folding_problem_solved = bool(direct_structure_solved or ensemble_contact_collapse_solved)
    folding_solution_mode = "unsolved"
    if direct_structure_solved and ensemble_contact_collapse_solved:
        folding_solution_mode = "direct_msa_free_structure_and_contact_ensemble"
    elif direct_structure_solved:
        folding_solution_mode = "direct_msa_free_single_sequence_structure"
    elif ensemble_contact_collapse_solved:
        folding_solution_mode = "contact_ensemble_collapse"

    script_safety_rejection = "none"
    if source_run.source_rejected:
        script_safety_rejection = source_run.status
    elif source_run.raw_sequence_exposed_in_persisted_artifacts:
        script_safety_rejection = "raw_sequence_persisted_by_keep_query_fasta"
    elif predictor_parse_error:
        script_safety_rejection = "single_sequence_prediction_pdb_parse_failed"
    elif report.independent_structure_pair_count <= 0:
        script_safety_rejection = source_run.status

    payload = {
        "kind": SINGLE_SEQUENCE_STRUCTURE_REPORT_KIND,
        "ensemble_kind": INDEPENDENT_CONTACT_ENSEMBLE_KIND,
        "row_id": row.row_id,
        "source_accession": row.source_accession,
        "event_source": args.event_source,
        "selected_event_count": len(events),
        "single_sequence_source_run": source_run.to_dict(),
        "predictor_parse_error": predictor_parse_error,
        "source_family_pair_counts": _family_counts(evidence),
        "selected_contact_map_hash": contact_map_hash(selected_pairs),
        "direct_structure_contact_map_hash": contact_map_hash(direct_structure_pairs),
        "direct_structure_metric": {
            **direct_structure_metric.to_dict(),
            "long_range_contact_precision": direct_long_precision,
            "claim_allowed": direct_structure_solved,
            "direct_structure_solved": direct_structure_solved,
            "solved_precision_threshold": args.solved_precision_threshold,
            "solved_recall_threshold": args.solved_recall_threshold,
        },
        "report": report.to_dict(),
        "selected_contacts": [decision.to_dict() for decision in selected_decisions],
        "safety": {
            "alphafold_used_by_this_script": bool(source_run.alphafold_like_source_id),
            "msa_used_by_this_script": False,
            "prediction_command_opt_in_only": True,
            "prediction_command_timeout_seconds": source_run.timeout_seconds,
            "prediction_command_timed_out": source_run.prediction_command_timed_out,
            "query_fasta_persisted": source_run.query_fasta_persisted,
            "raw_sequence_exposed_in_persisted_artifacts": source_run.raw_sequence_exposed_in_persisted_artifacts,
            "benchmark_claim_allowed_by_ensemble": report.benchmark_claim_allowed,
            "benchmark_claim_allowed_by_direct_structure": direct_structure_solved,
            "direct_structure_solved": direct_structure_solved,
            "ensemble_contact_collapse_solved": ensemble_contact_collapse_solved,
            "folding_solution_mode": folding_solution_mode,
            "script_safety_rejection": script_safety_rejection,
            "native_truth_used_before_selection": report.native_truth_used_before_selection,
            "coordinate_truth_used_before_selection": report.coordinate_truth_used_before_selection,
            "native_truth_attached_after_selection_for_evaluation": True,
            "folding_problem_solved": folding_problem_solved,
        },
    }

    report_path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    _csv_write(decisions_path, [decision.to_dict() for decision in decisions])
    _csv_write(selected_path, [decision.to_dict() for decision in selected_decisions])
    write_contact_evidence_json(
        evidence_path,
        evidence=tuple(evidence),
        source_kind="msa_free_single_sequence_structure_probe_evidence_bundle_v0",
    )

    print(json.dumps(payload["safety"], indent=2, sort_keys=True))
    print(json.dumps(payload["report"], indent=2, sort_keys=True))
    print(report_path)

    if args.fail_without_prediction and report.independent_structure_pair_count <= 0:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
